### ISSUE TITLE
Event Store table definition 

### ISSUE THREAD

**Issue by RhysC** [MatchaIO/ServerlessTimesheet#30]
1) range/sort index may be wrong
It should probably be the timestamp as we want this sorted. ie event coming out of order would not be ideal and i dont think we have that guarantee at the moment

ie 

```
KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: timestamp
            KeyType: RANGE

```

2) we should probably explicitly define both the `eventsMetadata` and the `event` payload "columns" as a [Map](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes.Document.Map) and not do the serialising ourselves
